name: Update

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Script
        run: |
          # Login to ghcr.io
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Fetch the latest tag
          tag=$(curl -s https://api.github.com/repos/openobserve/openobserve/releases/latest | jq -r .tag_name)
          
          # Pull the image from the original repository
          docker pull public.ecr.aws/zinclabs/openobserve:$tag
          docker pull public.ecr.aws/zinclabs/openobserve:$tag-simd
          
          # Retag the image for the new repository
          docker tag public.ecr.aws/zinclabs/openobserve:$tag ghcr.io/${{ github.actor }}/openobserve:$tag
          docker tag public.ecr.aws/zinclabs/openobserve:$tag ghcr.io/${{ github.actor }}/openobserve:latest
          docker tag public.ecr.aws/zinclabs/openobserve:$tag-simd ghcr.io/${{ github.actor }}/openobserve:$tag-simd
          docker tag public.ecr.aws/zinclabs/openobserve:$tag-simd ghcr.io/${{ github.actor }}/openobserve:latest-simd
          
          # Push the image to the new repository
          docker push ghcr.io/${{ github.actor }}/openobserve:$tag
          docker push ghcr.io/${{ github.actor }}/openobserve:latest
          docker push ghcr.io/${{ github.actor }}/openobserve:$tag-simd
          docker push ghcr.io/${{ github.actor }}/openobserve:latest-simd
